package lsremote

import (
	"bytes"
	"context"
	"encoding/hex"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/hiddeco/go-ls-remote/internal/wire"
	"github.com/hiddeco/go-ls-remote/pktline"
	"github.com/hiddeco/go-ls-remote/transport"
)

// benchRefSink defeats dead-code elimination on the per-ref drain loop.
// Without an observable use of every yielded Ref the compiler can erase
// parts of the iterator body that the benchmark is meant to measure.
var benchRefSink Ref

// benchCapsSink defeats dead-code elimination on Capabilities deep-copy
// benchmarks — without an assignment the return value may be optimised away.
var benchCapsSink Capabilities

// BenchmarkSession_Refs_v0_noSymrefs pins the steady-state cost of
// draining `refsCached` with the symrefs flag off. `refsCached` is the
// v0/v1 hot loop: on every `Session.Refs` call over a non-v2 connection
// the library scans `s.refs` once, applying a prefix filter and a
// per-ref copy. With `Symrefs: false` each ref clears its `Symref`
// field to the empty string and yields — no per-ref slice scan is
// performed, making this the simplest, cheapest code path.
//
// The fixture synthesises 101 refs (HEAD + 90 branches + 10 tags) to
// model a small-to-medium repository. A large monorepo enumeration
// (~10k refs) would close the gap to production scale; such a corpus
// can be generated by capturing the raw ref slice from a
// `git ls-remote --heads --tags` run against a mirror and unmarshalling
// it with `wire.ParseV0Advertisement`.
func BenchmarkSession_Refs_v0_noSymrefs(b *testing.B) {
	s := &Session{
		caps: Capabilities{
			Version:      ProtocolV0,
			ObjectFormat: ObjectFormatSHA1,
		},
		refs: synthRefs(b),
	}
	req := RefsRequest{} // Symrefs: false (zero value)

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		seq, err := s.Refs(b.Context(), req)
		if err != nil {
			b.Fatal(err)
		}
		for r, err := range seq {
			if err != nil {
				b.Fatal(err)
			}
			benchRefSink = r
		}
	}
}

// BenchmarkSession_Refs_v0_withSymrefs pins the steady-state cost of
// draining `refsCached` with the symrefs flag on. The B5 refactor
// introduced a per-ref linear scan over `s.caps.Symrefs` when
// `args.Symrefs == true`: for each yielded ref whose `Symref` field is
// empty, `symrefTarget` walks the `Symrefs` slice looking for a name
// match. The cost is O(refs × symrefs) per drain call; for typical
// repositories (hundreds of refs, 1–2 symrefs) it is negligible, but
// pinning it here means a future regression on N×M becomes quantitatively
// visible rather than an unnoticed drift.
//
// The fixture uses 2 symref entries (HEAD and refs/remotes/origin/HEAD),
// matching the common case of a single-remote checkout. A corpus
// generator that replays real v0 advertisements from `git upload-pack`
// would produce a more representative symref-to-ref ratio.
func BenchmarkSession_Refs_v0_withSymrefs(b *testing.B) {
	s := &Session{
		caps: Capabilities{
			Version:      ProtocolV0,
			ObjectFormat: ObjectFormatSHA1,
			Symrefs: []Symref{
				{Name: "HEAD", Target: "refs/heads/main"},
				{Name: "refs/remotes/origin/HEAD", Target: "refs/heads/main"},
			},
		},
		refs: synthRefs(b),
	}
	req := RefsRequest{Symrefs: true}

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		seq, err := s.Refs(b.Context(), req)
		if err != nil {
			b.Fatal(err)
		}
		for r, err := range seq {
			if err != nil {
				b.Fatal(err)
			}
			benchRefSink = r
		}
	}
}

// BenchmarkSession_Capabilities pins the per-call cost of the
// `Capabilities` method. The C3 refactor added a doc note that this
// method allocates a fresh deep copy on every call, because the returned
// value must be safe to mutate without affecting the Session's internal
// state. The copy allocates slices and a map proportional to the
// capabilities the server advertised.
//
// The fixture models a realistic v2 snapshot: 4 commands, 3 `ls-refs`
// args, 1 `object-info` arg, 0 symrefs, and 8 raw entries — the shape
// an average github.com or GitLab remote produces. Callers in hot loops
// should cache the returned value rather than calling this method
// repeatedly; this benchmark makes the allocation cost of ignoring that
// advice visible.
func BenchmarkSession_Capabilities(b *testing.B) {
	s := &Session{
		caps: Capabilities{
			Version:        ProtocolV2,
			Agent:          "git/2.44.0",
			ObjectFormat:   ObjectFormatSHA1,
			Commands:       []string{"ls-refs", "fetch", "object-info", "bundle-uri"},
			LSRefsArgs:     []string{"unborn", "peel", "symrefs"},
			ObjectInfoArgs: []string{"size"},
			Symrefs:        nil,
			Raw: map[string][]string{
				"agent":         {"git/2.44.0"},
				"object-format": {"sha1"},
				"ls-refs":       {"unborn peel symrefs"},
				"fetch":         {"shallow filter"},
				"object-info":   {"size"},
				"server-option": {""},
				"session-id":    {"abc123def456"},
				"bundle-uri":    {""},
			},
		},
	}

	// Verify the fixture is well-formed before entering the hot path.
	require.NotEmpty(b, s.caps.Commands)
	require.NotEmpty(b, s.caps.LSRefsArgs)

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		benchCapsSink = s.Capabilities()
	}
}

// synthRefs returns a slice of 101 synthetic Ref values: HEAD followed
// by 90 branch refs and 10 tag refs. The OIDs are stable across runs;
// the shape is representative of a small-to-medium repository. Symref
// and Peeled fields are left empty — the benchmark fills them in via
// the Session.Refs path under test.
func synthRefs(b *testing.B) []Ref {
	b.Helper()
	refs := make([]Ref, 0, 101)
	refs = append(refs, Ref{
		Name: "HEAD",
		Hash: benchSyntheticOID(0),
	})
	for i := range 90 {
		refs = append(refs, Ref{
			Name: fmt.Sprintf("refs/heads/branch-%d", i),
			Hash: benchSyntheticOID(uint64(i + 1)),
		})
	}
	for i := range 10 {
		refs = append(refs, Ref{
			Name: fmt.Sprintf("refs/tags/v0.%d.0", i),
			Hash: benchSyntheticOID(uint64(91 + i)),
		})
	}
	return refs
}

// benchSyntheticOID returns a deterministic 40-hex-char string keyed on
// seed. Matches the generation shape used in
// `internal/wire/refs_v2_bench_test.go::benchSyntheticHex` so the OID
// bytes drive the same code paths a real SHA-1 OID would.
func benchSyntheticOID(seed uint64) string {
	const hexChars = "0123456789abcdef"
	var out [40]byte
	for i := range out {
		out[i] = hexChars[(seed>>(uint(i%16)*4))&0xf]
	}
	for i := 16; i < 40; i++ {
		out[i] = hexChars[(seed*uint64(i+1))&0xf]
	}
	return string(out[:])
}

// BenchmarkSession_Refs_v2_emit pins the per-call cost of emitting a v2
// `ls-refs` command end-to-end through [Session.Refs]: the slice copies,
// string concatenations, and pkt-line framing performed by
// [wire.EncodeLSRefs] plus the iterator scaffolding [Session.refsV2]
// wraps around the response decoder. A discovery against an HTTP remote
// runs this path exactly once per `ls-refs` POST; the per-call CPU shape
// is what scales with the caller's prefix and toggle fan.
//
// The fixture wires a `reuseCommandConn` whose `Command` drains the
// body callback into a reused [pktline.Writer] over a reused
// [bytes.Buffer] and rewinds a reused [pktline.Reader] over a pre-canned
// flush-only response (`0000`). The flush is a valid `ls-refs` response
// per [gitprotocol-v2.adoc §"ls-refs"]: zero ref-lines followed by the
// terminating flush. The stub recycles its writer, reader, and source
// buffers across iterations so the bench reports the encoder's
// allocation pressure rather than the stub's setup cost. The
// `RawCapabilities` advertises a v2 capability list realistic enough
// for the cap-echo path in [wire.EncodeLSRefs] (`agent`,
// `object-format`, `ls-refs=unborn`).
//
// The request mirrors a typical discovery filter: two prefix args
// (`refs/heads/`, `refs/tags/`), `peel`, and `symrefs`. After the
// root-builder removal in the prior refactor and the per-line
// concatenation removal in the encoder migration, allocs/op should be a
// small constant independent of prefix count — the encoder writes each
// `ref-prefix <p>` line via [pktline.Writer.WriteLineParts] without
// intermediate string concatenation, and the writer's scratch buffer is
// reused across writes.
//
// [gitprotocol-v2.adoc §"ls-refs"]: https://github.com/git/git/blob/v2.54.0/Documentation/gitprotocol-v2.adoc#ls-refs
func BenchmarkSession_Refs_v2_emit(b *testing.B) {
	canned := flushOnlyResponse(b)
	conn := newReuseCommandConn(canned)
	s := &Session{
		conn: conn,
		caps: Capabilities{
			Version:      ProtocolV2,
			ObjectFormat: ObjectFormatSHA1,
		},
		rawCaps: wire.RawCapabilities{
			{Name: "agent", Value: "git/2.45.0"},
			{Name: "object-format", Value: "sha1"},
			{Name: "ls-refs", Value: "unborn"},
		},
	}
	args := RefsRequest{
		Prefixes: []string{"refs/heads/", "refs/tags/"},
		Peel:     true,
		Symrefs:  true,
	}
	ctx := b.Context()

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		seq, err := s.Refs(ctx, args)
		if err != nil {
			b.Fatal(err)
		}
		// Drain the iterator end-to-end so the bench captures the per-call
		// scaffolding cost (closure allocation, response decoder setup),
		// not just the request emission. The canned response is a bare
		// flush so the drain terminates immediately.
		for r, err := range seq {
			if err != nil {
				b.Fatal(err)
			}
			benchRefSink = r
		}
	}
}

// BenchmarkSession_ObjectInfo_emit pins the per-call cost of emitting a
// v2 `object-info` command end-to-end through [Session.ObjectInfo]: the
// per-OID `oid <hex>` line emission performed by [wire.EncodeObjectInfo]
// plus the response materialisation and the size-sentinel post-pass on
// the returned slice. A batch-metadata probe runs this path once per
// request; the per-OID emission cost is what scales with the caller's
// OID fan.
//
// The fixture wires a `reuseCommandConn` whose `Command` drains the
// body callback into a reused [pktline.Writer] over a reused
// [bytes.Buffer] and rewinds a reused [pktline.Reader] over a pre-canned
// flush-only response (`0000`). A bare flush is a valid `object-info`
// response per [protocol-caps.c::send_info lines 44-45] (the
// zero-OID-requested shape); the decoder returns `nil, nil` and the
// Session-level call completes with an empty slice. The stub recycles
// its writer, reader, and source buffers across iterations so the bench
// reports the encoder's allocation pressure rather than the stub's
// setup cost. The `RawCapabilities` carries `object-format=sha1` so the
// cap-echo path inside the encoder fires.
//
// The request enumerates 16 deterministic 40-hex-char OIDs with
// `Size: true`. After the per-line concatenation removal in the encoder
// migration, allocs/op should be a small constant independent of OID
// count — the encoder writes each `oid <hex>` line via
// [pktline.Writer.WriteLineParts] without intermediate string
// concatenation, and the writer's scratch buffer is reused across all
// per-OID lines.
//
// [protocol-caps.c::send_info lines 44-45]: https://github.com/git/git/blob/v2.54.0/protocol-caps.c#L44-L45
func BenchmarkSession_ObjectInfo_emit(b *testing.B) {
	canned := flushOnlyResponse(b)
	conn := newReuseCommandConn(canned)
	s := &Session{
		conn: conn,
		caps: Capabilities{
			Version:      ProtocolV2,
			ObjectFormat: ObjectFormatSHA1,
		},
		rawCaps: wire.RawCapabilities{
			{Name: "agent", Value: "git/2.45.0"},
			{Name: "object-format", Value: "sha1"},
			{Name: "object-info", Value: "size"},
		},
	}
	oids := benchObjectInfoOIDs(16)
	args := ObjectInfoRequest{Size: true}
	ctx := b.Context()

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		infos, err := s.ObjectInfo(ctx, oids, args)
		if err != nil {
			b.Fatal(err)
		}
		benchObjectInfoSliceSink = infos
	}
}

// benchObjectInfoSliceSink defeats dead-code elimination on the
// `ObjectInfo` return value — without an observable assignment the
// compiler can erase parts of the call the bench is meant to measure.
var benchObjectInfoSliceSink []ObjectInfo

// benchObjectInfoOIDs builds n deterministic 40-hex-char OID strings
// keyed on index. The bytes are not a real SHA-1 over any object — the
// encoder treats OIDs as opaque hex, so any 40-char hex run drives the
// emission path a real OID would.
func benchObjectInfoOIDs(n int) []string {
	out := make([]string, n)
	for i := range out {
		var b [20]byte
		b[19] = byte(i)
		out[i] = hex.EncodeToString(b[:])
	}
	return out
}

// flushOnlyResponse builds a pre-canned wire response carrying nothing
// but a flush packet. It is a valid `ls-refs` response (zero ref-lines
// followed by the terminating flush, per
// [gitprotocol-v2.adoc §"ls-refs"]) and a valid `object-info` response
// (the zero-OID shape per [protocol-caps.c::send_info lines 44-45]).
// Built once per bench and handed to `reuseCommandConn` so the response
// side of the wire exchange is constant; the bench measures the request
// side.
//
// [gitprotocol-v2.adoc §"ls-refs"]: https://github.com/git/git/blob/v2.54.0/Documentation/gitprotocol-v2.adoc#ls-refs
// [protocol-caps.c::send_info lines 44-45]: https://github.com/git/git/blob/v2.54.0/protocol-caps.c#L44-L45
func flushOnlyResponse(b *testing.B) []byte {
	b.Helper()
	var buf bytes.Buffer
	pw := pktline.NewWriter(&buf)
	if err := pw.WriteFlush(); err != nil {
		b.Fatal(err)
	}
	return buf.Bytes()
}

// reuseCommandConn is a benchmark-only [transport.Conn] stub whose
// `Command` drains the body callback into a reused [pktline.Writer]
// over a reused [bytes.Buffer] and returns a reused [pktline.Reader]
// rewound onto the pre-canned response bytes. The per-call setup that
// `fakeCommandConn` performs — allocating a fresh writer, a fresh
// [bytes.Reader], and a fresh [pktline.Reader] — is hoisted into the
// stub's construction so steady-state benchmarks observe only the
// encoder's own allocation pressure, not the stub's overhead.
//
// The contract on [transport.Conn.Command] is preserved: the body
// callback is invoked exactly once per call against a writer the
// caller can drive freely, and the returned reader carries the next
// command's response framing. Re-running `Command` rewinds the source
// buffer to position 0 so the same canned bytes are replayed each
// iteration; the writer's underlying buffer is reset to zero length so
// it does not grow without bound across iterations.
type reuseCommandConn struct {
	canned []byte
	src    *bytes.Reader
	rdr    *pktline.Reader
	bodyW  *pktline.Writer
	bodyB  *bytes.Buffer
}

// newReuseCommandConn returns a `reuseCommandConn` whose `Command`
// replays canned as the response stream on every call. The writer side
// is allocated once at construction; the source buffer is pre-positioned
// at canned so the first `Command` invocation sees the full response.
func newReuseCommandConn(canned []byte) *reuseCommandConn {
	src := bytes.NewReader(canned)
	bodyB := new(bytes.Buffer)
	return &reuseCommandConn{
		canned: canned,
		src:    src,
		rdr:    pktline.NewReader(src),
		bodyW:  pktline.NewWriter(bodyB),
		bodyB:  bodyB,
	}
}

func (c *reuseCommandConn) Advertisement() *pktline.Reader {
	return pktline.NewReader(bytes.NewReader(nil))
}

func (c *reuseCommandConn) Command(_ context.Context, _ string,
	body transport.CommandBody,
) (*pktline.Reader, error) {
	c.bodyB.Reset()
	if err := body(c.bodyW); err != nil {
		return nil, err
	}
	c.src.Reset(c.canned)
	return c.rdr, nil
}

func (c *reuseCommandConn) Close() error { return nil }
