package lsremote

import (
	"context"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
)

// benchRefSink defeats dead-code elimination on the per-ref drain loop.
// Without an observable use of every yielded Ref the compiler can erase
// parts of the iterator body that the benchmark is meant to measure.
var benchRefSink Ref

// benchCapsSink defeats dead-code elimination on Capabilities deep-copy
// benchmarks — without an assignment the return value may be optimised away.
var benchCapsSink Capabilities

// BenchmarkSession_Refs_v0_noSymrefs pins the steady-state cost of
// draining `refsCached` with the symrefs flag off. `refsCached` is the
// v0/v1 hot loop: on every `Session.Refs` call over a non-v2 connection
// the library scans `s.refs` once, applying a prefix filter and a
// per-ref copy. With `Symrefs: false` each ref clears its `Symref`
// field to the empty string and yields — no per-ref slice scan is
// performed, making this the simplest, cheapest code path.
//
// The fixture synthesises 101 refs (HEAD + 90 branches + 10 tags) to
// model a small-to-medium repository. A large monorepo enumeration
// (~10k refs) would close the gap to production scale; such a corpus
// can be generated by capturing the raw ref slice from a
// `git ls-remote --heads --tags` run against a mirror and unmarshalling
// it with `wire.ParseV0Advertisement`.
func BenchmarkSession_Refs_v0_noSymrefs(b *testing.B) {
	s := &Session{
		caps: Capabilities{
			Version:      ProtocolV0,
			ObjectFormat: ObjectFormatSHA1,
		},
		refs: synthRefs(b),
	}
	req := RefsRequest{} // Symrefs: false (zero value)

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		seq, err := s.Refs(context.Background(), req)
		if err != nil {
			b.Fatal(err)
		}
		for r, err := range seq {
			if err != nil {
				b.Fatal(err)
			}
			benchRefSink = r
		}
	}
}

// BenchmarkSession_Refs_v0_withSymrefs pins the steady-state cost of
// draining `refsCached` with the symrefs flag on. The B5 refactor
// introduced a per-ref linear scan over `s.caps.Symrefs` when
// `args.Symrefs == true`: for each yielded ref whose `Symref` field is
// empty, `symrefTarget` walks the `Symrefs` slice looking for a name
// match. The cost is O(refs × symrefs) per drain call; for typical
// repositories (hundreds of refs, 1–2 symrefs) it is negligible, but
// pinning it here means a future regression on N×M becomes quantitatively
// visible rather than an unnoticed drift.
//
// The fixture uses 2 symref entries (HEAD and refs/remotes/origin/HEAD),
// matching the common case of a single-remote checkout. A corpus
// generator that replays real v0 advertisements from `git upload-pack`
// would produce a more representative symref-to-ref ratio.
func BenchmarkSession_Refs_v0_withSymrefs(b *testing.B) {
	s := &Session{
		caps: Capabilities{
			Version:      ProtocolV0,
			ObjectFormat: ObjectFormatSHA1,
			Symrefs: []Symref{
				{Name: "HEAD", Target: "refs/heads/main"},
				{Name: "refs/remotes/origin/HEAD", Target: "refs/heads/main"},
			},
		},
		refs: synthRefs(b),
	}
	req := RefsRequest{Symrefs: true}

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		seq, err := s.Refs(context.Background(), req)
		if err != nil {
			b.Fatal(err)
		}
		for r, err := range seq {
			if err != nil {
				b.Fatal(err)
			}
			benchRefSink = r
		}
	}
}

// BenchmarkSession_Capabilities pins the per-call cost of the
// `Capabilities` method. The C3 refactor added a doc note that this
// method allocates a fresh deep copy on every call, because the returned
// value must be safe to mutate without affecting the Session's internal
// state. The copy allocates slices and a map proportional to the
// capabilities the server advertised.
//
// The fixture models a realistic v2 snapshot: 4 commands, 3 `ls-refs`
// args, 1 `object-info` arg, 0 symrefs, and 8 raw entries — the shape
// an average github.com or GitLab remote produces. Callers in hot loops
// should cache the returned value rather than calling this method
// repeatedly; this benchmark makes the allocation cost of ignoring that
// advice visible.
func BenchmarkSession_Capabilities(b *testing.B) {
	s := &Session{
		caps: Capabilities{
			Version:        ProtocolV2,
			Agent:          "git/2.44.0",
			ObjectFormat:   ObjectFormatSHA1,
			Commands:       []string{"ls-refs", "fetch", "object-info", "bundle-uri"},
			LSRefsArgs:     []string{"unborn", "peel", "symrefs"},
			ObjectInfoArgs: []string{"size"},
			Symrefs:        nil,
			Raw: map[string][]string{
				"agent":         {"git/2.44.0"},
				"object-format": {"sha1"},
				"ls-refs":       {"unborn peel symrefs"},
				"fetch":         {"shallow filter"},
				"object-info":   {"size"},
				"server-option": {""},
				"session-id":    {"abc123def456"},
				"bundle-uri":    {""},
			},
		},
	}

	// Verify the fixture is well-formed before entering the hot path.
	require.NotEmpty(b, s.caps.Commands)
	require.NotEmpty(b, s.caps.LSRefsArgs)

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		benchCapsSink = s.Capabilities()
	}
}

// synthRefs returns a slice of 101 synthetic Ref values: HEAD followed
// by 90 branch refs and 10 tag refs. The OIDs are stable across runs;
// the shape is representative of a small-to-medium repository. Symref
// and Peeled fields are left empty — the benchmark fills them in via
// the Session.Refs path under test.
func synthRefs(b *testing.B) []Ref {
	b.Helper()
	refs := make([]Ref, 0, 101)
	refs = append(refs, Ref{
		Name: "HEAD",
		Hash: benchSyntheticOID(0),
	})
	for i := range 90 {
		refs = append(refs, Ref{
			Name: fmt.Sprintf("refs/heads/branch-%d", i),
			Hash: benchSyntheticOID(uint64(i + 1)),
		})
	}
	for i := range 10 {
		refs = append(refs, Ref{
			Name: fmt.Sprintf("refs/tags/v0.%d.0", i),
			Hash: benchSyntheticOID(uint64(91 + i)),
		})
	}
	return refs
}

// benchSyntheticOID returns a deterministic 40-hex-char string keyed on
// seed. Matches the generation shape used in
// `internal/wire/refs_v2_bench_test.go::benchSyntheticHex` so the OID
// bytes drive the same code paths a real SHA-1 OID would.
func benchSyntheticOID(seed uint64) string {
	const hexChars = "0123456789abcdef"
	var out [40]byte
	for i := range out {
		out[i] = hexChars[(seed>>(uint(i%16)*4))&0xf]
	}
	for i := 16; i < 40; i++ {
		out[i] = hexChars[(seed*uint64(i+1))&0xf]
	}
	return string(out[:])
}
